services:
  - type: web
    name: exl-demos
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python serve.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
